<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\ActivityCategory;

class ActivityCategorySeeder extends Seeder
{
    public function run()
    {
        $activities = [
            'Engineering Team Report/CAP Follow-up',
            'Inspection notification sending',
            'LoR Issue',
            'No-Color/structural completion letter Issue',
            'Report dispatch',
            'Report dispatch Tracker Update',
            'Report upload in FFC',
            'Consultation (RPD) (Inspection Scheduling)',
            'Email Review (Inspection Scheduling)',
            'Overseeing Inspection confirmation (Inspection Scheduling)',
            'Phone Calls (Inspection Scheduling)',
            'Boiler CAP fill up',
            'Boiler Immediate Issue Follow Up',
            'Boiler Initial CAP Follow up (Factory)',
            'Boiler initial CAP prepare, review and publish',
            'Boiler Initial Report dispatch',
            'Boiler Preparation Checklist and Online Meeting Invitation',
            'Boiler Survey Follow Up',
            'CAP Publish',
            'CAP review',
            'CAP update email to factory',
            'Closure-Relocation Brand confirmation email',
            'Closure-Relocation factsheet',
            'Closure-Relocation follow up',
            'Closure-Relocation meeting',
            'Closure-Relocation meeting action point',
            'Closure-Relocation ownership follow up',
            'Closure-Relocation verification report',
            'Closure-Relocation verification visit',
            'CMT Update',
            'Contribution Collection',
            'De-escalation letter',
            'De-escalation Recommendation',
            'Doc Pre-Submission Meeting Invitation',
            'Doc Pre-Submission Meeting Minutes',
            'Email Review',
            'Engagement (Brand)',
            'Engineering Team Design Review Follow-up',
            'Engineering Team Meeting Follow-up',
            'Escalation - EAF Review',
            'Escalation (1 & 2) Follow up',
            'Escalation Pre stage 2 factsheet',
            'Escalation pre-stage 2 meeting',
            'Escalation pre-stage 2 meeting minutes',
            'Escalation stage 1 factsheet',
            'Escalation stage 1 meeting',
            'Escalation stage 1 meeting minutes',
            'Escalation stage 2 advance meeting',
            'Escalation stage 2 advance meeting minutes',
            'Escalation stage 2 factsheet',
            'Escalation stage 2 meeting',
            'Escalation stage 2 meeting minutes',
            'Escalation stage 3 recommendation',
            'Escalation stage 3 requalification',
            'Extension case meeting',
            'Extension case meeting minutes',
            'Extension follow up',
            'Factory area follow up',
            'Factory area-EIF',
            'Factory Group information update',
            'Factory Handover',
            'Factory list review follow up',
            'Factory list review meeting',
            'FADS,SUPS,SFP,PFP,EA,DEA,SLD doc collection,sent for review, Follow-up for re-submission and in put CMT',
            'FADS-SUPS initial design follow up',
            'FADS-SUPS T&CVI follow up',
            'FADS-SUPS Warning',
            'FFC data update',
            'Finance factsheet',
            'Finance follow up',
            'Finance meeting',
            'Finance meeting minutes',
            'Finance Plan Agreement',
            'Finance pre-submission meeting',
            'Immediate issue follow up',
            'Inspection confirmation',
            'Inspection draft checking',
            'LoR recommendation',
            'Meeting with CSO',
            'No-Color/structural completion letter Assessment',
            'Phone Calls',
            'Post-Incident Follow up',
            'Post-Incident Report Issue',
            'Pre-Initial Inspection Survey',
            'Query & task (Brand)',
            'Query & task (Factory)',
            'Stage 2 Advance meeting',
            'Stage 2 Advance meeting Action point',
            'Stage 2 group factory information email to RPO',
            'Team Meeting',
            'Technical query follow up',
            'Technical query meeting',
            'Technical query meeting minutes',
            'Tracker Contact update',
            'Tracker Draft inspection check',
            'Tracker update (All) Meeting',
            'Training participation',
            'Workshop email and follow up call',
            'GIZ SCAIP project Coordination',
            'FFC Data interpretation & development activities',
            'Database Development Activity',
            'DIFE-Coordination & Focal Point',
            'GCC-Coordination & Preparedness',
            'Organizational dashboard preparation for decisions',
            'IA-Communication & Coordination (Database, SOP, Protocol)',
            'Coaching/mentoring colleagues in relevant processes',
            'Stakeholder Engagement-Brand',
            'Stakeholder Engagement-Factory',
            'Strategic Meeting (HoD, CSO, MD)',
            'Planning & facilitating executive meetings for MD',
            'Circulating executive meeting agendas and minutes',
            'Prepare and present RSC update in different forums',
            'Internal coordination for daily reporting (Inspection, Complaint, Training) & cross-department support',
            'Departmental Budget implementation',
            'Procurement Committee engagement',
            'Advising on organizational data representation for public disclosure',
            'Overseeing & advising in the GIZ SCAIP project activities',
            'Analyzing data for priority setting & decision making',
            'Identifying gaps and recommending corrective actions',
            'Preparing periodic status/progress report on RSC Inspection & Remediation',
            'Special investigation as assigned by MD',
            'Collaboration & dispute resolution',
            'Team development (awareness, knowledge-sharing, mentoring)',
            'Preparing communication materials (email & memos)',
            'Responding to queries and providing requested information',
            'Customer engagement Brand',
            'Customer engagement Factory',
            'Stakeholder Engagement (DIFE)',
            'Stakeholder Engagement (GCC)',
            'Stakeholder Engagement (BGMEA & BKMEA)',
            'Stakeholder Engagement (IA)',
            'Ensuring adherence to organizational policies and regulations',
            'Identifying risks and escalating issues for management action',
            'Strategic Planning & Policy formulation (incl. OSH Training & Complaints)',
            'Suggesting innovations and improvements in workflows',
            'Inspection date upload',
            'Inspection draft preparing',
            'Inspection schedule finalization',
            'LoR Assessment',
            'LoR Programme',
            'Consultation (FESB)',
            'Email Review (Remediation Mailbox)',
            'Consultation (RPD-Inspection Scheduling)',
            'Factory area follow up (Inspection Scheduling)',
            'FFC data download (Inspection Scheduling)',
            'FFC data update (Inspection Scheduling)',
            'FFC Factory Data wrangling (Inspection Scheduling)',
            'Inspection draft checking (Inspection Scheduling)',
            'Inspection notification sending (Inspection Scheduling)',
            'Meeting with CSO (Inspection Scheduling)',
            'No-Color/structural completion letter Review',
            'Query & task (Brand) (Inspection Scheduling)',
            'Query & task (CSO) (Inspection Scheduling)',
            'Query & task (Factory) (Inspection Scheduling)',
            'Query & task (Sr. HoD) (Inspection Scheduling)',
            'RSC monthly report data validation (Inspection Scheduling)',
            'SOP, Protocol & Flowchart (Inspection Scheduling)',
            'Team Meeting (Inspection Scheduling)',
            'Tracker Contact update (Inspection Scheduling)',
            'Tracker Draft inspection check (Inspection Scheduling)',
            'Boiler Immediate issue & Non critical issue meeting with Boiler department',
            'Boiler Immediate issue follow up with RPO and boiler department',
            'Boiler Immediate issue listing, Email drafting,',
            'Boiler inspection (I&H, Functional) Tracker',
            'Boiler inspection follow up',
            'Boiler preparation meeting listing and send to boiler department and RPO',
            'CAP Categorization tracking',
            'CAP Regulation (Updating, Commenting & Escalation)',
            'Closure-Relocation IBC communication',
            'Consultation (RPD)',
            'Escalation - EAF Review (Escalation Team)',
            'Escalation (1 & 2) Letter issue',
            'Escalation data update (Tracker & FFC)',
            'Escalation KPI report preparation',
            'Escalation Stage-01 meeting schedule & tracking weekly',
            'Extension factory initial research and FFC data update',
            'Factory area-survey',
            'Factory newly listed tracker update',
            'Factory Orientation Conduction',
            'Factory Orientation PPT development',
            'Factory Union information update',
            'FFC data download',
            'FFC Factory Data wrangling',
            'Finance document review',
            'Finance trackers',
            'Immediate issue management',
            'Independent factory initial research',
            'Initial Research email sent for newly listed factory',
            'Monthly Delay Report on FADS, SUPS, D/EA, SLD & Others (SFP,PFP, Racking)',
            'Non BBR Follow up RPO,',
            'Non BBR listing, Email drafting,',
            'Overseeing Area Information',
            'Overseeing boiler inspection preparedness',
            'Overseeing FADS, SUPS, D/EA, SLD & Others (SFP,PFP, Racking)',
            'Overseeing Finance Protocol',
            'Pre-Initial Inspection Brand Confirmation',
            'Pre-Initial Inspection Factory Confirmation',
            'Prepare, draft & checking the boiler inspection notification emails as per received proposed boiler inspection schedules from BSE team',
            'Query & task (CSO)',
            'Query & task (International Accord)',
            'Query & task (Sr. HoD)',
            'Query (Website/Contacts/Direct email)',
            'Schedule Alignment & inspection notification drafting (addition/postponement/replacement)',
            'Schedule of Pre Stage 2 from 3 HOD',
            'Sent email for IA for merge or delete duplicate ID',
            'Sent email to IA for ID activation',
            'SOP, Protocol & Flowchart',
            'Tracking Boiler CAPs review',
            'Tracking Boiler CAPs upload',
            'Tracking Boiler reports delivery',
            'Training coordination',
            'Training Providing',
            'Training Recordkeeping',
            'Union data alignment with training dept',
            'Union information update on FFC',
            'Assigning & reassigning publisher',
            'Assigning & reassigning RPO',
            'CAP & date delete in FFC',
            'Closure-Relocation Communication with IA & RSC Concern (Pending Closure, Closed, Active, Inactive Responsible, No Brand, Delete, Archived)',
            'Closure-Relocation factsheet Review',
            'Closure-Relocation follow up with RPOs',
            'Closure-Relocation meeting minutes review',
            'Closure-Relocation review of Final Closure Summary',
            'Closure-Relocation transfer to DIFE',
            'Closure-Relocation verification report review',
            'Closure-Relocation verification visit Scheduling',
            'Escalation (3) Letter issue',
            'Escalation stage 3 transfer to DIFE',
            'Escalation stage 3 UD suspension',
            'Extension (EIF processing for extension covered as FUIN)',
            'Extension (EIF Processing for New ID recommendation)',
            'Extension (EIF Processing)',
            'Extension account creation',
            'FFC tickets',
            'FFC user management',
            'Independent factory listing',
            'Inspection date upload (CVV & OVV)',
            'Non RSC Factory listing information',
            'Oversee Industry engagement (BGMEA & BKMEA)',
            'Overseeing Case Management Tool',
            'Overseeing Closure-Relocation Protocol',
            'Overseeing Escalation & De-escalation Protocol',
            'Overseeing Extension Protocol',
            'Overseeing Factory Membership status (BGMEA/BKMEA/BEZA/BEPZA)',
            'Overseeing Independent factory onboarding process',
            'Overseeing Inspection Scheduling Protocol (F, E, S, B)',
            'Overseeing Project 90-99%',
            'Overseeing Task Management Tool',
            'Query & task (DIFE)',
            'Query & task (MD)',
            'Report delete',
            'RSC monthly report data validation this values'
        ];

        foreach ($activities as $activity) {
            ActivityCategory::create([
                'name' => $activity,
                'definition' => null,
                'reference_protocol' => null,
                'objective' => null,
                'standard_time' => null,
                'code' => null, // Will be auto-generated
                'department_id' => null,
                'parent_id' => null
            ]);
        }
    }
}
